server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: criptomoedas
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/crypto_transactions}
    username: ${SPRING_DATASOURCE_USERNAME:crypto}
    password: ${SPRING_DATASOURCE_PASSWORD:crypto}
  flyway:
    enabled: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    default-property-inclusion: non_null

binance:
  api:
    base-url: ${BINANCE_API_BASE_URL:https://api.binance.com}

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    com.vitorvidal.criptomoedas: INFO
